name = "av5ja"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-05-13"
send_metrics = true
kv_namespaces = [
  { binding = "RESULTS", id = "c7c2262b7c3e4bf9af607b726cf84a53" },
  { binding = "SCHEDULES", id = "bc10803207b245e79c684b0e7954e6dc" },
  { binding = "USERS", id = "9dba38122605448f8f63f6c4bafce01c" },
  { binding = "RESOURCES", id = "7aed7afef4a24816ac7a7ab5a835d580" },
  { binding = "CACHES", id = "bbbe36203fcb4f62b93e4eade0e23e73" },
]

[triggers]
crons = ["*/30 * * * *"]

[env.dev]
workers_dev = true
kv_namespaces = [
  { binding = "RESULTS", id = "c7c2262b7c3e4bf9af607b726cf84a53" },
  { binding = "SCHEDULES", id = "bc10803207b245e79c684b0e7954e6dc" },
  { binding = "USERS", id = "9dba38122605448f8f63f6c4bafce01c" },
  { binding = "RESOURCES", id = "7aed7afef4a24816ac7a7ab5a835d580" },
  { binding = "CACHES", id = "bbbe36203fcb4f62b93e4eade0e23e73" },
]
