services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 18787:8787
    volumes:
      - node_modules:/home/vscode/app/node_modules
      - ../:/home/vscode/app:cached
    tty: true
    stdin_open: true

volumes:
  node_modules:
