services:
  hono:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUN_VERSION: 1.1.26
        NODE_VERSION: 20.16.0
    ports:
      - 18787:18787
    volumes:
      - node_modules:/home/bun/app/node_modules
      - ../:/home/bun/app:cached
    tty: true
    stdin_open: true

volumes:
  node_modules:
