name: Continuous Deployment

on:
  push:
    branches:
      - '**'
      - 'main'
      - 'master'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          no-cache: false

      - name: Install
        run: |
          bun install --frozen-lockfile --ignore-scripts

      - name: Format and Lint
        run: |
          bun run format
          bun run lint

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: |
          bun install --frozen-lockfile --ignore-scripts

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          accountId: ${{ secrets.CLOUDFLARE_API_TOKEN }
